parameters:
  start_crank_speed:
    label: 起始曲柄角速度
    value: -2
    unit: rad/s
    initial_state:
      joint: crank_hinge
      field: qvel
  start_rod_speed:
    label: 起始连杆相对角速度
    value: 1.5231782849660247
    unit: rad/s
    initial_state:
      joint: rod_hinge_a
      field: qvel
  start_orbit_speed:
    label: 起始圆心轨道角速度
    value: 0.9779642198726407
    unit: rad/s
    initial_state:
      joint: disk_orbit
      field: qvel
  start_spin_speed:
    label: 起始圆盘相对角速度
    value: -1.9559284397452814
    unit: rad/s
    initial_state:
      joint: disk_spin
      field: qvel
